/**
 * THIS FILE IS GENERATED BY setup-styles.ts
 * DO NOT EDIT IT DIRECTLY.
 */

import href0 from "@fontsource-variable/geist/files/geist-latin-wght-normal.woff2?url"
import href1 from "@fontsource/geist-pixel/files/geist-pixel-latin-400-normal.woff2?url"
import href2 from "@fontsource-variable/geist-mono/files/geist-mono-latin-wght-normal.woff2?url"

export const fontPreloadHrefs = [href0, href1, href2]