export {
  autoRefresh,
  type CreateGsapOptions,
  createGsap,
  createGsapContext,
  createGsapMatchMedia,
  type Gsap,
  type GsapContext,
  type GsapMatchMedia,
  type GsapPluginName,
  getGsap,
  getScrollTrigger,
  hasPlugin,
  loadGsap,
  loadScrollTrigger,
  MOTION_OK,
  MOTION_REDUCED,
  prefersReducedMotion,
  refreshOnFontsReady,
  refreshOnResize,
  type ScrollTriggerStatic,
  setGsapLoader,
  setGsapPluginLoader,
} from "./gsap"
export {
  destroySmoothScroll,
  getLenis,
  initSmoothScroll,
  LENIS_CSS,
  type LenisInstance,
  type LenisOptions,
  loadLenis,
  SmoothScroll,
  type SmoothScrollOptions,
  type SmoothScrollProps,
} from "./lenis"
export type { TickCallback, TickerSource } from "./ticker"
export { addTick, hasTickerSource, removeTick, setTickerSource } from "./ticker"
