import { writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

import * as config from "../config"
import { generateRoot } from "./generate-root"
import { generateScale } from "./generate-scale"
import { generateTailwind } from "./generate-tailwind"

const banner = `/*
 * THIS FILE IS GENERATED BY setup-styles.ts
 * DO NOT EDIT IT DIRECTLY.
 */`

export const OUTPUTS = {
  tailwind: "src/styles/css/tailwind.css",
  root: "src/styles/css/root.css",
} as const

/**
 * Build the generated stylesheets in memory, without touching disk.
 *
 * Kept pure so `setup-styles.test.ts` can assert the committed CSS still
 * matches what the current palette and config produce.
 */
export function buildStyleSheets() {
  return {
    tailwind: [banner, generateTailwind(config), generateScale()].join("\n\n"),
    root: [banner, generateRoot(config)].join("\n\n"),
  }
}

// Run-as-script detection that works under Bun and Node (`tsx`/`node`) alike,
// replacing Bun's `import.meta.main`.
const invokedDirectly =
  process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1]

if (invokedDirectly) {
  const { tailwind, root } = buildStyleSheets()

  writeFileSync(`./${OUTPUTS.tailwind}`, tailwind)
  writeFileSync(`./${OUTPUTS.root}`, root)

  // eslint-disable-next-line no-console
  console.log("\u2713 Style config generated successfully")
}
