import { writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

import * as config from "../config"
import { generateFonts } from "./generate-fonts"
import { generateRoot } from "./generate-root"
import { generateScale } from "./generate-scale"
import { generateTailwind } from "./generate-tailwind"

const cssBanner = `/*
 * THIS FILE IS GENERATED BY setup-styles.ts
 * DO NOT EDIT IT DIRECTLY.
 */`

const tsBanner = `/**
 * THIS FILE IS GENERATED BY setup-styles.ts
 * DO NOT EDIT IT DIRECTLY.
 */`

export const OUTPUTS = {
  tailwind: "src/styles/css/tailwind.css",
  root: "src/styles/css/root.css",
  fonts: "src/styles/css/fonts.css",
  fontPreloads: "src/styles/font-preloads.ts",
} as const

/**
 * Build the generated stylesheets in memory, without touching disk.
 *
 * Kept pure so `setup-styles.test.ts` can assert the committed CSS still
 * matches what the current palette and config produce.
 */
export function buildStyleSheets() {
  const fonts = generateFonts()

  return {
    tailwind: [cssBanner, generateTailwind(config), generateScale()].join("\n\n"),
    root: [cssBanner, generateRoot(config)].join("\n\n"),
    fonts: [cssBanner, fonts.css].join("\n\n"),
    fontPreloads: [tsBanner, fonts.preloads].join("\n\n"),
  }
}

// Run-as-script detection that works under Bun and Node (`tsx`/`node`) alike,
// replacing Bun's `import.meta.main`.
const invokedDirectly =
  process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1]

if (invokedDirectly) {
  const { tailwind, root, fonts, fontPreloads } = buildStyleSheets()

  writeFileSync(`./${OUTPUTS.tailwind}`, tailwind)
  writeFileSync(`./${OUTPUTS.root}`, root)
  writeFileSync(`./${OUTPUTS.fonts}`, fonts)
  writeFileSync(`./${OUTPUTS.fontPreloads}`, fontPreloads)

  // eslint-disable-next-line no-console
  console.log("\u2713 Style config generated successfully")
}
